# Generated by Django 3.0.1 on 2020-01-05 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author_name', models.CharField(blank=True, max_length=200)),
                ('date_posted', models.DateField(default=datetime.date(2020, 1, 5), editable=False)),
                ('image', models.ImageField(upload_to='static/')),
                ('ingredients', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
